Vagrant.configure("2") do |config|

	config.vm.box = "bstoots/xubuntu-16.04-desktop-amd64"
	config.vm.network "private_network", type: "dhcp"

	config.vm.provider "virtualbox" do |vb|
	    vb.gui = true
	    vb.memory = "2048"
	    vb.name = "we45-aws-vm"
	    vb.customize ['modifyvm', :id, '--clipboard', 'bidirectional']
  	end

  	config.vm.provision :shell, path: "install_aws_baseline.sh"

end